name: etdemands
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - geopandas
  - numpy
  - openpyxl
  - pandas
  - pyshp
  - pytest
  - python=3.8
  - rtree
  - shapely
  - xlrd
  - requests
  - tk
